steps:
  # Create docker image from regular Dockerfile
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '--tag=gcr.io/$PROJECT_ID/init-actions-image', '-f', 'cloudbuild/Dockerfile', '.']

  # Run presubmit script
  - name: 'gcr.io/$PROJECT_ID/init-actions-image'
    entrypoint: 'bash'
    args: ['cloudbuild/presubmit.sh']
