steps:
  # Create Docker image from regular Dockerfile
  - name: 'gcr.io/cloud-builders/docker'
    id: 'docker-build'
    args: ['build', '--tag=gcr.io/$PROJECT_ID/init-actions-image:$BUILD_ID', '-f', 'cloudbuild/Dockerfile', '.']

  # Push Docker image to GCR
  - name: 'gcr.io/cloud-builders/docker'
    id: 'gcr-push'
    args: ['push', 'gcr.io/$PROJECT_ID/init-actions-image:$BUILD_ID']

  # Run presubmit tests in parallel for 2.0 Debian image
  - name: 'gcr.io/cloud-builders/kubectl'
    id: 'dataproc-2.0-debian10-tests'
    waitFor: ['gcr-push']
    entrypoint: 'bash'
    args: ['cloudbuild/run-presubmit-on-k8s.sh', 'gcr.io/$PROJECT_ID/init-actions-image:$BUILD_ID', '$BUILD_ID', '2.0-debian10']
    env:
      - 'COMMIT_SHA=$COMMIT_SHA'
      - 'CLOUDSDK_COMPUTE_REGION=us-central1'
      - 'CLOUDSDK_CONTAINER_CLUSTER=init-actions-presubmit'

  # Run presubmit tests in parallel for 2.0 Rocky Linux image
  - name: 'gcr.io/cloud-builders/kubectl'
    id: 'dataproc-2.0-rocky8-tests'
    waitFor: ['gcr-push']
    entrypoint: 'bash'
    args: ['cloudbuild/run-presubmit-on-k8s.sh', 'gcr.io/$PROJECT_ID/init-actions-image:$BUILD_ID', '$BUILD_ID', '2.0-rocky8']
    env:
      - 'COMMIT_SHA=$COMMIT_SHA'
      - 'CLOUDSDK_COMPUTE_REGION=us-central1'
      - 'CLOUDSDK_CONTAINER_CLUSTER=init-actions-presubmit'

  # Run presubmit tests in parallel for 2.0 Ubuntu image
  - name: 'gcr.io/cloud-builders/kubectl'
    id: 'dataproc-2.0-ubuntu18-tests'
    waitFor: ['gcr-push']
    entrypoint: 'bash'
    args: ['cloudbuild/run-presubmit-on-k8s.sh', 'gcr.io/$PROJECT_ID/init-actions-image:$BUILD_ID', '$BUILD_ID', '2.0-ubuntu18']
    env:
      - 'COMMIT_SHA=$COMMIT_SHA'
      - 'CLOUDSDK_COMPUTE_REGION=us-central1'
      - 'CLOUDSDK_CONTAINER_CLUSTER=init-actions-presubmit'

# Run presubmit tests in parallel for 2.1 Debian image
  - name: 'gcr.io/cloud-builders/kubectl'
    id: 'dataproc-2.1-debian11-tests'
    waitFor: ['gcr-push']
    entrypoint: 'bash'
    args: ['cloudbuild/run-presubmit-on-k8s.sh', 'gcr.io/$PROJECT_ID/init-actions-image:$BUILD_ID', '$BUILD_ID', '2.1-debian11']
    env:
    - 'COMMIT_SHA=$COMMIT_SHA'
    - 'CLOUDSDK_COMPUTE_REGION=us-central1'
    - 'CLOUDSDK_CONTAINER_CLUSTER=init-actions-presubmit'

# Run presubmit tests in parallel for 2.1 Rocky Linux image
  - name: 'gcr.io/cloud-builders/kubectl'
    id: 'dataproc-2.1-rocky8-tests'
    waitFor: ['gcr-push']
    entrypoint: 'bash'
    args: ['cloudbuild/run-presubmit-on-k8s.sh', 'gcr.io/$PROJECT_ID/init-actions-image:$BUILD_ID', '$BUILD_ID', '2.1-rocky8']
    env:
    - 'COMMIT_SHA=$COMMIT_SHA'
    - 'CLOUDSDK_COMPUTE_REGION=us-central1'
    - 'CLOUDSDK_CONTAINER_CLUSTER=init-actions-presubmit'

# Run presubmit tests in parallel for 2.1 Ubuntu image
  - name: 'gcr.io/cloud-builders/kubectl'
    id: 'dataproc-2.1-ubuntu20-tests'
    waitFor: ['gcr-push']
    entrypoint: 'bash'
    args: ['cloudbuild/run-presubmit-on-k8s.sh', 'gcr.io/$PROJECT_ID/init-actions-image:$BUILD_ID', '$BUILD_ID', '2.1-ubuntu20']
    env:
    - 'COMMIT_SHA=$COMMIT_SHA'
    - 'CLOUDSDK_COMPUTE_REGION=us-central1'
    - 'CLOUDSDK_CONTAINER_CLUSTER=init-actions-presubmit'

  # Run presubmit tests in parallel for 2.2 Debian image
  - name: 'gcr.io/cloud-builders/kubectl'
    id: 'dataproc-2.2-debian12-tests'
    waitFor: ['gcr-push']
    entrypoint: 'bash'
    args: ['cloudbuild/run-presubmit-on-k8s.sh', 'gcr.io/$PROJECT_ID/init-actions-image:$BUILD_ID', '$BUILD_ID', '2.2-debian12']
    env:
      - 'COMMIT_SHA=$COMMIT_SHA'
      - 'CLOUDSDK_COMPUTE_REGION=us-central1'
      - 'CLOUDSDK_CONTAINER_CLUSTER=init-actions-presubmit'

  # Run presubmit tests in parallel for 2.2 Rocky Linux image
  - name: 'gcr.io/cloud-builders/kubectl'
    id: 'dataproc-2.2-rocky9-tests'
    waitFor: ['gcr-push']
    entrypoint: 'bash'
    args: ['cloudbuild/run-presubmit-on-k8s.sh', 'gcr.io/$PROJECT_ID/init-actions-image:$BUILD_ID', '$BUILD_ID', '2.2-rocky9']
    env:
      - 'COMMIT_SHA=$COMMIT_SHA'
      - 'CLOUDSDK_COMPUTE_REGION=us-central1'
      - 'CLOUDSDK_CONTAINER_CLUSTER=init-actions-presubmit'

  # Run presubmit tests in parallel for 2.2 Ubuntu image
  - name: 'gcr.io/cloud-builders/kubectl'
    id: 'dataproc-2.2-ubuntu22-tests'
    waitFor: ['gcr-push']
    entrypoint: 'bash'
    args: ['cloudbuild/run-presubmit-on-k8s.sh', 'gcr.io/$PROJECT_ID/init-actions-image:$BUILD_ID', '$BUILD_ID', '2.2-ubuntu22']
    env:
      - 'COMMIT_SHA=$COMMIT_SHA'
      - 'CLOUDSDK_COMPUTE_REGION=us-central1'
      - 'CLOUDSDK_CONTAINER_CLUSTER=init-actions-presubmit'

  # Delete Docker image from GCR
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['container', 'images', 'delete', 'gcr.io/$PROJECT_ID/init-actions-image:$BUILD_ID']

timeout: 14400s
