steps:
  # Create Docker image from regular Dockerfile
  - name: 'gcr.io/cloud-builders/docker'
    id: 'docker-build'
    args: ['build', '--tag=gcr.io/$PROJECT_ID/init-actions-image:$BUILD_ID', '-f', 'cloudbuild/Dockerfile', '.']

  # Push Docker image to GCR
  - name: 'gcr.io/cloud-builders/docker'
    id: 'gcr-push'
    args: ['push', 'gcr.io/$PROJECT_ID/init-actions-image:$BUILD_ID']

  # Run presubmit tests in parallel for 1.3 Debian image
  - name: 'gcr.io/cloud-builders/kubectl'
    id: 'dataproc-1.3-debian10-tests'
    waitFor: ['gcr-push']
    entrypoint: 'bash'
    args: ['cloudbuild/run-presubmit-on-k8s.sh', 'gcr.io/$PROJECT_ID/init-actions-image:$BUILD_ID', '$BUILD_ID', '1.3-debian10']
    env:
      - 'COMMIT_SHA=$COMMIT_SHA'
      - 'CLOUDSDK_COMPUTE_REGION=us-west1'
      - 'CLOUDSDK_CONTAINER_CLUSTER=init-actions-presubmit'

  # Run presubmit tests in parallel for 1.3 Ubuntu image
  - name: 'gcr.io/cloud-builders/kubectl'
    id: 'dataproc-1.3-ubuntu18-tests'
    waitFor: ['gcr-push']
    entrypoint: 'bash'
    args: ['cloudbuild/run-presubmit-on-k8s.sh', 'gcr.io/$PROJECT_ID/init-actions-image:$BUILD_ID', '$BUILD_ID', '1.3-ubuntu18']
    env:
      - 'COMMIT_SHA=$COMMIT_SHA'
      - 'CLOUDSDK_COMPUTE_REGION=us-west1'
      - 'CLOUDSDK_CONTAINER_CLUSTER=init-actions-presubmit'

  # Run presubmit tests in parallel for 1.4 Debian image
  - name: 'gcr.io/cloud-builders/kubectl'
    id: 'dataproc-1.4-debian10-tests'
    waitFor: ['gcr-push']
    entrypoint: 'bash'
    args: ['cloudbuild/run-presubmit-on-k8s.sh', 'gcr.io/$PROJECT_ID/init-actions-image:$BUILD_ID', '$BUILD_ID', '1.4-debian10']
    env:
      - 'COMMIT_SHA=$COMMIT_SHA'
      - 'CLOUDSDK_COMPUTE_REGION=us-west1'
      - 'CLOUDSDK_CONTAINER_CLUSTER=init-actions-presubmit'

  # Run presubmit tests in parallel for 1.4 Ubuntu image
  - name: 'gcr.io/cloud-builders/kubectl'
    id: 'dataproc-1.4-ubuntu18-tests'
    waitFor: ['gcr-push']
    entrypoint: 'bash'
    args: ['cloudbuild/run-presubmit-on-k8s.sh', 'gcr.io/$PROJECT_ID/init-actions-image:$BUILD_ID', '$BUILD_ID', '1.4-ubuntu18']
    env:
      - 'COMMIT_SHA=$COMMIT_SHA'
      - 'CLOUDSDK_COMPUTE_REGION=us-west1'
      - 'CLOUDSDK_CONTAINER_CLUSTER=init-actions-presubmit'

  # Run presubmit tests in parallel for 1.5 CentOS image
  - name: 'gcr.io/cloud-builders/kubectl'
    id: 'dataproc-1.5-centos8-tests'
    waitFor: ['gcr-push']
    entrypoint: 'bash'
    args: ['cloudbuild/run-presubmit-on-k8s.sh', 'gcr.io/$PROJECT_ID/init-actions-image:$BUILD_ID', '$BUILD_ID', '1.5-centos8']
    env:
      - 'COMMIT_SHA=$COMMIT_SHA'
      - 'CLOUDSDK_COMPUTE_REGION=us-west1'
      - 'CLOUDSDK_CONTAINER_CLUSTER=init-actions-presubmit'

  # Run presubmit tests in parallel for 1.5 Debian image
  - name: 'gcr.io/cloud-builders/kubectl'
    id: 'dataproc-1.5-debian10-tests'
    waitFor: ['gcr-push']
    entrypoint: 'bash'
    args: ['cloudbuild/run-presubmit-on-k8s.sh', 'gcr.io/$PROJECT_ID/init-actions-image:$BUILD_ID', '$BUILD_ID', '1.5-debian10']
    env:
      - 'COMMIT_SHA=$COMMIT_SHA'
      - 'CLOUDSDK_COMPUTE_REGION=us-west1'
      - 'CLOUDSDK_CONTAINER_CLUSTER=init-actions-presubmit'

  # Run presubmit tests in parallel for 1.5 Ubuntu image
  - name: 'gcr.io/cloud-builders/kubectl'
    id: 'dataproc-1.5-ubuntu18-tests'
    waitFor: ['gcr-push']
    entrypoint: 'bash'
    args: ['cloudbuild/run-presubmit-on-k8s.sh', 'gcr.io/$PROJECT_ID/init-actions-image:$BUILD_ID', '$BUILD_ID', '1.5-ubuntu18']
    env:
      - 'COMMIT_SHA=$COMMIT_SHA'
      - 'CLOUDSDK_COMPUTE_REGION=us-west1'
      - 'CLOUDSDK_CONTAINER_CLUSTER=init-actions-presubmit'

  # Run presubmit tests in parallel for 2.0 Debian image
  - name: 'gcr.io/cloud-builders/kubectl'
    id: 'dataproc-2.0-debian10-tests'
    waitFor: ['gcr-push']
    entrypoint: 'bash'
    args: ['cloudbuild/run-presubmit-on-k8s.sh', 'gcr.io/$PROJECT_ID/init-actions-image:$BUILD_ID', '$BUILD_ID', '2.0-debian10']
    env:
      - 'COMMIT_SHA=$COMMIT_SHA'
      - 'CLOUDSDK_COMPUTE_REGION=us-west1'
      - 'CLOUDSDK_CONTAINER_CLUSTER=init-actions-presubmit'

  # Run presubmit tests in parallel for 2.0 Ubuntu image
  - name: 'gcr.io/cloud-builders/kubectl'
    id: 'dataproc-2.0-ubuntu18-tests'
    waitFor: ['gcr-push']
    entrypoint: 'bash'
    args: ['cloudbuild/run-presubmit-on-k8s.sh', 'gcr.io/$PROJECT_ID/init-actions-image:$BUILD_ID', '$BUILD_ID', '2.0-ubuntu18']
    env:
      - 'COMMIT_SHA=$COMMIT_SHA'
      - 'CLOUDSDK_COMPUTE_REGION=us-west1'
      - 'CLOUDSDK_CONTAINER_CLUSTER=init-actions-presubmit'

  # Delete Docker image from GCR
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['container', 'images', 'delete', 'gcr.io/$PROJECT_ID/init-actions-image:$BUILD_ID']

timeout: 5400s
