steps:
  # Create Docker image from regular Dockerfile
  - name: 'gcr.io/cloud-builders/docker'
    id: 'docker-build'
    args: ['build', '--tag=gcr.io/$PROJECT_ID/init-actions-image:$BUILD_ID', '-f', 'cloudbuild/Dockerfile', '.']

  # Push Docker image to GCR
  - name: 'gcr.io/cloud-builders/docker'
    id: 'gcr-push'
    args: ['push', 'gcr.io/$PROJECT_ID/init-actions-image:$BUILD_ID']

  # Run presubmit tests in parallel for 1.2 image
  - name: 'gcr.io/cloud-builders/kubectl'
    id: 'dataproc-1.2-tests'
    waitFor: ['gcr-push']
    entrypoint: 'bash'
    args: ['cloudbuild/run-presubmit-on-k8s.sh', 'gcr.io/$PROJECT_ID/init-actions-image:$BUILD_ID', '$BUILD_ID', '1.2']
    env:
      - 'COMMIT_SHA=$COMMIT_SHA'
      - 'CLOUDSDK_COMPUTE_ZONE=us-central1-f'
      - 'CLOUDSDK_CONTAINER_CLUSTER=init-actions-presubmit'

  # Run presubmit tests in parallel for 1.3 image
  - name: 'gcr.io/cloud-builders/kubectl'
    id: 'dataproc-1.3-tests'
    waitFor: ['gcr-push']
    entrypoint: 'bash'
    args: ['cloudbuild/run-presubmit-on-k8s.sh', 'gcr.io/$PROJECT_ID/init-actions-image:$BUILD_ID', '$BUILD_ID', '1.3']
    env:
      - 'COMMIT_SHA=$COMMIT_SHA'
      - 'CLOUDSDK_COMPUTE_ZONE=us-central1-f'
      - 'CLOUDSDK_CONTAINER_CLUSTER=init-actions-presubmit'

  # Run presubmit tests in parallel for 1.4 image
  - name: 'gcr.io/cloud-builders/kubectl'
    id: 'dataproc-1.4-tests'
    waitFor: ['gcr-push']
    entrypoint: 'bash'
    args: ['cloudbuild/run-presubmit-on-k8s.sh', 'gcr.io/$PROJECT_ID/init-actions-image:$BUILD_ID', '$BUILD_ID', '1.4']
    env:
      - 'COMMIT_SHA=$COMMIT_SHA'
      - 'CLOUDSDK_COMPUTE_ZONE=us-central1-f'
      - 'CLOUDSDK_CONTAINER_CLUSTER=init-actions-presubmit'

  # Delete Docker image from GCR
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['container', 'images', 'delete', 'gcr.io/$PROJECT_ID/init-actions-image:$BUILD_ID']

timeout: 5400s
