steps:

# Create docker image from regular Dockerfile
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--tag=gcr.io/google.com/hadoop-cloud-dev/init-actions-image', '.']
# Run the test from the repo
- name: 'gcr.io/google.com/hadoop-cloud-dev/init-actions-image'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    [[ "$BRANCH_NAME" =~ .*bigtable.* ]] && python bigtable/test_bigtable.py 

# images:
# - 'gcr.io/google.com/hadoop-cloud-dev/init-actions-image'