steps:

# Create docker image from regular Dockerfile
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--tag=gcr.io/google.com/hadoop-cloud-dev/init-actions-image', '.']
  id: 'create_image'
# Run tests from the repo, based on the branch name
- name: 'gcr.io/google.com/hadoop-cloud-dev/init-actions-image'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    [[ "$BRANCH_NAME" == .*bigtable.* ]] && python bigtable/test_bigtable.py || [[ "$BRANCH_NAME" != .*bigtable.* ]]
  waitFor: ['create_image']
- name: 'gcr.io/google.com/hadoop-cloud-dev/init-actions-image'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    [[ "$BRANCH_NAME" == .*drill.* ]] && python drill/test_drill.py || [[ "$BRANCH_NAME" != .*drill.* ]]
  waitFor: ['create_image']
- name: 'gcr.io/google.com/hadoop-cloud-dev/init-actions-image'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    [[ "$BRANCH_NAME" == .*flink.* ]] && python flink/test_flink.py || [[ "$BRANCH_NAME" != .*flink.* ]]
  waitFor: ['create_image']
- name: 'gcr.io/google.com/hadoop-cloud-dev/init-actions-image'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    [[ "$BRANCH_NAME" == .*ganglia.* ]] && python ganglia/test_ganglia.py || [[ "$BRANCH_NAME" != .*ganglia.* ]]
  waitFor: ['create_image']
- name: 'gcr.io/google.com/hadoop-cloud-dev/init-actions-image'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    [[ "$BRANCH_NAME" == .*gpu.* ]] && python gpu/test_install_gpu_driver.py || [[ "$BRANCH_NAME" != .*gpu.* ]]
  waitFor: ['create_image']
- name: 'gcr.io/google.com/hadoop-cloud-dev/init-actions-image'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    [[ "$BRANCH_NAME" == .*hbase.* ]] && python hbase/test_hbase.py || [[ "$BRANCH_NAME" != .*hbase.* ]]
  waitFor: ['create_image']
- name: 'gcr.io/google.com/hadoop-cloud-dev/init-actions-image'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    [[ "$BRANCH_NAME" == .*hive.* ]] && python hive-hcatalog/test_hive.py || [[ "$BRANCH_NAME" != .*hive.* ]]
  waitFor: ['create_image']
- name: 'gcr.io/google.com/hadoop-cloud-dev/init-actions-image'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    [[ "$BRANCH_NAME" == .*hue.* ]] && python hue/test_hue.py || [[ "$BRANCH_NAME" != .*hue.* ]]
  waitFor: ['create_image']
- name: 'gcr.io/google.com/hadoop-cloud-dev/init-actions-image'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    [[ "$BRANCH_NAME" == .*kafka.* ]] && python kafka/test_kafka.py || [[ "$BRANCH_NAME" != .*kafka.* ]]
  waitFor: ['create_image']
- name: 'gcr.io/google.com/hadoop-cloud-dev/init-actions-image'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    [[ "$BRANCH_NAME" == .*livy.* ]] && python livy/test_livy.py || [[ "$BRANCH_NAME" != .*livy.* ]]
  waitFor: ['create_image']
- name: 'gcr.io/google.com/hadoop-cloud-dev/init-actions-image'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    [[ "$BRANCH_NAME" == .*oozie.* ]] && python oozie/test_oozie.py || [[ "$BRANCH_NAME" != .*oozie.* ]]
  waitFor: ['create_image']
- name: 'gcr.io/google.com/hadoop-cloud-dev/init-actions-image'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    [[ "$BRANCH_NAME" == .*presto.* ]] && python presto/test_presto.py || [[ "$BRANCH_NAME" != .*presto.* ]]
  waitFor: ['create_image']
- name: 'gcr.io/google.com/hadoop-cloud-dev/init-actions-image'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    [[ "$BRANCH_NAME" == .*ranger.* ]] && python ranger/test_ranger.py || [[ "$BRANCH_NAME" != .*ranger.* ]]
  waitFor: ['create_image']
- name: 'gcr.io/google.com/hadoop-cloud-dev/init-actions-image'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    [[ "$BRANCH_NAME" == .*solr.* ]] && python solr/test_solr.py || [[ "$BRANCH_NAME" != .*solr.* ]]
  waitFor: ['create_image']
- name: 'gcr.io/google.com/hadoop-cloud-dev/init-actions-image'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    [[ "$BRANCH_NAME" == .*starburst.* ]] && python starburst-presto/test_presto.py || [[ "$BRANCH_NAME" != .*starburst.* ]]
  waitFor: ['create_image']
- name: 'gcr.io/google.com/hadoop-cloud-dev/init-actions-image'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    [[ "$BRANCH_NAME" == .*tez.* ]] && python tez/test_tez.py || [[ "$BRANCH_NAME" != .*tez.* ]]
  waitFor: ['create_image']
- name: 'gcr.io/google.com/hadoop-cloud-dev/init-actions-image'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    [[ "$BRANCH_NAME" == .*tony.* ]] && python tony/test_tony.py || [[ "$BRANCH_NAME" != .*tony.* ]]
  waitFor: ['create_image']
