steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/google.com/hadoop-cloud-dev/dataproc-init-actions-image', '.' ]
images:
- 'gcr.io/google.com/hadoop-cloud-dev/dataproc-init-actions-image'