presubmits:
  ishanrc/dataproc-initialization-actions:
  - name: test-flink
    always_run: true
    agent: kubernetes
    labels:
      preset-service-account: "true"
    spec:
      containers:
      - image: gcr.io/dataproc-kokoro-tests/test-container
        command: ["/home/test/run_tests.sh"]
        imagePullPolicy: Always
        env:
        - name: TEST_MODULE
          value: flink.test_flink
