package(default_visibility = ["//visibility:public"])

py_library(
	name = "dataproc_test_case",
	srcs = ["dataproc_test_case.py"],
	deps = ["@io_abseil_py//absl/flags"]
)

exports_files(["requirements.txt"])