package(default_visibility = ["//visibility:public"])

py_library(
    name = "dataproc_test_case",
    testonly = True,
    srcs = ["dataproc_test_case.py"],
    deps = [
        "@io_abseil_py//absl/flags",
        "@io_abseil_py//absl/testing:parameterized",
    ],
)
