name: rapids
channels:
  - rapidsai/label/xgboost
  - rapidsai/label/cuda10.0
  - nvidia
  - conda-forge
  - numba
  - pytorch
dependencies:
  - python=3.7
  - cudatoolkit=10.0
  - dask-cuda=0.7.*
  - cudf=0.7.*
  - dask-cudf=0.7.*
  - cuml=0.7.*
  - dask-cuml=0.7.*
  - cugraph=0.7.*
  - rapidsai/label/xgboost::xgboost=0.83.*
  - rapidsai/label/xgboost::dask-xgboost=0.2.*
  - cython
  - dask
  - distributed
  - gcsfs
