#!/usr/bin/env python
#
# Copyright 2013 Google Inc. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""A wrapper for running bdconfig with simplified import-path setup."""

import os
import platform
import subprocess
import sys

# Checks the Python version.
if not hasattr(sys, 'version_info'):
  sys.stderr.write('Very old versions of Python are not supported. Please '
                   'use version 2.6 or greater.\n')
  sys.exit(1)
if tuple(sys.version_info[:2]) < (2, 6):
  sys.stderr.write('Python %d.%d is not supported. Please use version 2.6 '
                   'or greater.\n' % tuple(sys.version_info[:2]))
  sys.exit(1)


def main():
  """Launches bdconfig using python -S.

  The -S ensures that the site module is not imported and eliminates a
  class of problems that can occur when the user's system has multiple
  versions of a library.
  """
  python_bin = sys.executable
  if not python_bin:
    sys.stderr.write('Could not find Python executable.')
    sys.exit(1)

  bdconfig_main = os.path.join(
      os.path.dirname(os.path.realpath(__file__)),
      'lib',
      'google_hadoop',
      'bdconfig_lib',
      'bdconfig.py')
  args = [python_bin, '-S', bdconfig_main] + sys.argv[1:]
  if platform.system() == 'Windows':
    subprocess.Popen(args).wait()
  else:
    os.execv(python_bin, args)


if __name__ == '__main__':
  main()
